"""
Skill Executor

Loads and executes structured skill workflows against document sections,
generating findings with skill provenance and framework mappings.
"""

import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from pathlib import Path

from skill_index import SkillMetadata


@dataclass
class SkillFinding:
    """Finding generated by skill execution"""
    id: str
    origin: str = "skill_executor"
    skill_id: str = ""
    skill_name: str = ""
    skill_domain: str = ""
    issue: str = ""
    severity: str = "MEDIUM"
    evidence_excerpt: str = ""
    mitre_attack: List[str] = None
    nist_csf: List[str] = None
    nist_ai_rmf: List[str] = None
    mitre_d3fend: List[str] = None
    frameworks: List[str] = None
    standard_reference: str = ""
    recommendation: str = ""
    finding_count: int = 0

    def __post_init__(self):
        if self.mitre_attack is None:
            self.mitre_attack = []
        if self.nist_csf is None:
            self.nist_csf = []
        if self.nist_ai_rmf is None:
            self.nist_ai_rmf = []
        if self.mitre_d3fend is None:
            self.mitre_d3fend = []
        if self.frameworks is None:
            self.frameworks = []

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'id': self.id,
            'origin': self.origin,
            'skill_id': self.skill_id,
            'skill_name': self.skill_name,
            'skill_domain': self.skill_domain,
            'issue': self.issue,
            'severity': self.severity,
            'evidence_excerpt': self.evidence_excerpt,
            'mitre_attack': self.mitre_attack,
            'nist_csf': self.nist_csf,
            'nist_ai_rmf': self.nist_ai_rmf,
            'mitre_d3fend': self.mitre_d3fend,
            'frameworks': self.frameworks,
            'standard_reference': self.standard_reference,
            'recommendation': self.recommendation,
            'finding_count': self.finding_count,
        }


class SkillExecutor:
    """Execute skill workflows against document sections"""

    # Severity order for filtering
    SEVERITY_ORDER = {'CRITICAL': 4, 'HIGH': 3, 'MEDIUM': 2, 'LOW': 1}

    # Pattern mapping for common security checks
    PATTERN_CHECKS = {
        # AWS IAM patterns
        'aws_wildcard_action': {
            'pattern': r'"(?:Action|action)"?\s*:\s*["\']?\*["\']?',
            'issue': 'Overly permissive IAM action (Action: *)',
            'severity': 'CRITICAL',
        },
        'aws_wildcard_resource': {
            'pattern': r'"(?:Resource|resource)"?\s*:\s*["\']?\*["\']?',
            'issue': 'Overly permissive resource scope (Resource: *)',
            'severity': 'CRITICAL',
        },
        'aws_inline_policy': {
            'pattern': r'AWS::IAM::(?:UserPolicy|RolePolicy)',
            'issue': 'Inline IAM policy used (should use managed policies)',
            'severity': 'HIGH',
        },
        # Network patterns
        'permit_any_any': {
            'pattern': r'permit\s+(?:ip|tcp|udp)\s+any\s+any',
            'issue': 'Over-permissive firewall rule (permit any any)',
            'severity': 'CRITICAL',
        },
        'telnet_enabled': {
            'pattern': r'(?:telnet|Telnet)\s+(?:enabled|allowed|open)',
            'issue': 'Telnet cleartext protocol enabled (should use SSH)',
            'severity': 'CRITICAL',
        },
        'ftp_backup': {
            'pattern': r'(?:FTP|ftp)\s+(?:backup|upload|config)',
            'issue': 'FTP used for sensitive transfer (should use SFTP/SCP)',
            'severity': 'CRITICAL',
        },
        'snmpv1_v2c': {
            'pattern': r'SNMPv(?:1|2c)|community\s+string',
            'issue': 'SNMPv1/v2c cleartext protocol used (should use SNMPv3)',
            'severity': 'HIGH',
        },
        # Application patterns
        'no_mfa_admin': {
            'pattern': r'(?:admin|administrator).*(?:login|access)\s+(?:without|no)\s+(?:MFA|2FA)',
            'issue': 'Administrative access without MFA enforcement',
            'severity': 'CRITICAL',
        },
        'credentials_in_code': {
            'pattern': r'(?:password|secret|api.?key|token)\s*=\s*["\'][^"\']{6,}["\']',
            'issue': 'Credentials hardcoded in configuration/code',
            'severity': 'CRITICAL',
        },
        'no_csrf_token': {
            'pattern': r'(?:form|POST)\s+(?:without|no)\s+(?:CSRF|csrf)\s+(?:token|protection)',
            'issue': 'Missing CSRF token protection on state-changing requests',
            'severity': 'HIGH',
        },
    }

    def __init__(self, skill: SkillMetadata):
        """
        Initialize executor for a skill.

        Args:
            skill: SkillMetadata loaded from skill index
        """
        self.skill = skill
        self.findings: List[SkillFinding] = []

    def execute(self, section_text: str, section_name: str = "") -> List[SkillFinding]:
        """
        Execute skill workflow against a document section.

        Args:
            section_text: Text content of document section
            section_name: Name/title of section for context

        Returns:
            List of findings generated by skill execution
        """
        findings = []

        # Extract workflow steps from skill markdown
        workflow_steps = self._extract_workflow_steps(self.skill.full_content)

        # Execute pattern matching for each workflow step
        for step_num, step in enumerate(workflow_steps, 1):
            step_findings = self._execute_step(
                section_text,
                step,
                step_num,
                section_name
            )
            findings.extend(step_findings)

        return findings

    def _extract_workflow_steps(self, skill_content: str) -> List[Dict[str, str]]:
        """
        Extract workflow steps from skill markdown.

        Args:
            skill_content: Full SKILL.md content

        Returns:
            List of workflow steps with description and checks
        """
        steps = []

        # Split by H3 headers (### Step N:)
        parts = re.split(r'### Step \d+:?\s*(.+?)\n', skill_content)

        # Process pairs of (title, content)
        for i in range(1, len(parts), 2):
            if i + 1 < len(parts):
                title = parts[i].strip()
                content = parts[i + 1].strip()

                steps.append({
                    'title': title,
                    'content': content,
                    'patterns': self._extract_patterns(content)
                })

        return steps

    def _extract_patterns(self, step_content: str) -> List[str]:
        """
        Extract security patterns to check from step content.

        Returns:
            List of pattern names to check
        """
        patterns = []

        # Check predefined patterns
        for pattern_name in self.PATTERN_CHECKS.keys():
            # Simple heuristic: check if pattern name keywords appear in step
            keywords = pattern_name.split('_')
            if any(kw in step_content.lower() for kw in keywords):
                patterns.append(pattern_name)

        return patterns

    def _execute_step(
        self,
        section_text: str,
        step: Dict,
        step_num: int,
        section_name: str
    ) -> List[SkillFinding]:
        """
        Execute a single workflow step.

        Args:
            section_text: Document section to analyze
            step: Workflow step with title, content, patterns
            step_num: Step number for finding ID
            section_name: Name of section being analyzed

        Returns:
            List of findings from this step
        """
        findings = []

        # Check patterns defined for this step
        for pattern_name in step.get('patterns', []):
            if pattern_name not in self.PATTERN_CHECKS:
                continue

            pattern_def = self.PATTERN_CHECKS[pattern_name]
            pattern = pattern_def['pattern']
            issue = pattern_def['issue']
            severity = pattern_def['severity']

            # Search for pattern matches in section
            matches = list(re.finditer(pattern, section_text, re.IGNORECASE))

            for match_idx, match in enumerate(matches):
                # Extract evidence excerpt (surrounding context)
                start = max(0, match.start() - 100)
                end = min(len(section_text), match.end() + 100)
                evidence_excerpt = section_text[start:end].strip()

                finding_id = (
                    f"{self.skill.name}_{section_name}_"
                    f"step{step_num}_match{match_idx}"
                )

                finding = SkillFinding(
                    id=finding_id,
                    skill_id=self.skill.name,
                    skill_name=self.skill.name,
                    skill_domain=self.skill.domain,
                    issue=issue,
                    severity=severity,
                    evidence_excerpt=evidence_excerpt[:200],
                    mitre_attack=self.skill.mitre_attack.copy(),
                    nist_csf=self.skill.nist_csf.copy(),
                    nist_ai_rmf=self.skill.nist_ai_rmf.copy(),
                    mitre_d3fend=self.skill.mitre_d3fend.copy(),
                    frameworks=self.skill.frameworks.copy(),
                    standard_reference=self.skill.domain,
                    recommendation=f"See {self.skill.name} SKILL.md for remediation steps",
                    finding_count=match_idx + 1,
                )

                findings.append(finding)

        return findings

    def execute_custom_check(
        self,
        section_text: str,
        check_name: str,
        pattern_regex: str,
        issue: str,
        severity: str = "MEDIUM"
    ) -> List[SkillFinding]:
        """
        Execute a custom pattern check.

        Args:
            section_text: Document section to analyze
            check_name: Name of the check
            pattern_regex: Regex pattern to match
            issue: Description of issue if found
            severity: Severity level

        Returns:
            List of findings from this check
        """
        findings = []

        matches = list(re.finditer(pattern_regex, section_text, re.IGNORECASE))

        for match_idx, match in enumerate(matches):
            start = max(0, match.start() - 100)
            end = min(len(section_text), match.end() + 100)
            evidence_excerpt = section_text[start:end].strip()

            finding = SkillFinding(
                id=f"{self.skill.name}_{check_name}_{match_idx}",
                skill_id=self.skill.name,
                skill_name=self.skill.name,
                skill_domain=self.skill.domain,
                issue=issue,
                severity=severity,
                evidence_excerpt=evidence_excerpt[:200],
                mitre_attack=self.skill.mitre_attack.copy(),
                nist_csf=self.skill.nist_csf.copy(),
                frameworks=self.skill.frameworks.copy(),
                finding_count=match_idx + 1,
            )

            findings.append(finding)

        return findings

    @staticmethod
    def filter_findings(
        findings: List[SkillFinding],
        min_severity: Optional[str] = None,
        domains: Optional[List[str]] = None
    ) -> List[SkillFinding]:
        """
        Filter findings by severity and domain.

        Args:
            findings: List of findings to filter
            min_severity: Minimum severity level
            domains: List of allowed domains

        Returns:
            Filtered findings
        """
        filtered = findings

        # Filter by severity
        if min_severity and min_severity in SkillExecutor.SEVERITY_ORDER:
            min_score = SkillExecutor.SEVERITY_ORDER[min_severity]
            filtered = [
                f for f in filtered
                if SkillExecutor.SEVERITY_ORDER.get(f.severity, 0) >= min_score
            ]

        # Filter by domain
        if domains:
            domains_lower = [d.lower() for d in domains]
            filtered = [
                f for f in filtered
                if f.skill_domain.lower() in domains_lower
            ]

        return filtered

    @staticmethod
    def deduplicate_findings(findings: List[SkillFinding]) -> List[SkillFinding]:
        """
        Remove duplicate findings.

        Args:
            findings: List of findings

        Returns:
            Deduplicated findings (keeps first occurrence)
        """
        seen = set()
        unique = []

        for finding in findings:
            # Create fingerprint from issue + evidence
            fingerprint = (
                finding.skill_id,
                finding.issue,
                finding.severity,
                finding.evidence_excerpt[:50]
            )

            if fingerprint not in seen:
                seen.add(fingerprint)
                unique.append(finding)

        return unique


if __name__ == '__main__':
    # Example usage
    from skill_index import SkillIndex

    # Load index
    index = SkillIndex('/tmp/work/skills')

    # Get a skill
    skill = index.get_skill_by_name('detecting-cloud-iam-misconfigurations')
    if skill:
        executor = SkillExecutor(skill)

        # Test section
        test_section = """
        AWS IAM Configuration:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "*",
              "Resource": "*"
            }
          ]
        }
        """

        findings = executor.execute(test_section, "iam_config")
        print(f"Found {len(findings)} issues:")
        for finding in findings:
            print(f"  - [{finding.severity}] {finding.issue}")
            print(f"    Evidence: {finding.evidence_excerpt[:100]}...")
