"""
Skill Executor v2 - With TIER 1 Hardening

- Error handling for all pattern matching operations
- Timeout protection to prevent hanging
- State bounding to limit memory usage
- Pattern validation to prevent ReDoS attacks
- Logging for observability
"""

import re
import logging
import threading
import queue
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from pathlib import Path
import sys

from .skill_index import SkillMetadata
from .pattern_validator import PatternValidator, PatternDatabase

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='[%(levelname)s] %(name)s - %(message)s'
)
logger = logging.getLogger(__name__)


@dataclass
class SkillFinding:
    """Finding generated by skill execution"""
    id: str
    origin: str = "skill_executor"
    skill_id: str = ""
    skill_name: str = ""
    skill_domain: str = ""
    issue: str = ""
    severity: str = "MEDIUM"
    evidence_excerpt: str = ""
    mitre_attack: List[str] = None
    nist_csf: List[str] = None
    nist_ai_rmf: List[str] = None
    mitre_d3fend: List[str] = None
    frameworks: List[str] = None
    standard_reference: str = ""
    recommendation: str = ""
    finding_count: int = 0

    def __post_init__(self):
        if self.mitre_attack is None:
            self.mitre_attack = []
        if self.nist_csf is None:
            self.nist_csf = []
        if self.nist_ai_rmf is None:
            self.nist_ai_rmf = []
        if self.mitre_d3fend is None:
            self.mitre_d3fend = []
        if self.frameworks is None:
            self.frameworks = []

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'id': self.id,
            'origin': self.origin,
            'skill_id': self.skill_id,
            'skill_name': self.skill_name,
            'skill_domain': self.skill_domain,
            'issue': self.issue,
            'severity': self.severity,
            'evidence_excerpt': self.evidence_excerpt,
            'mitre_attack': self.mitre_attack,
            'nist_csf': self.nist_csf,
            'nist_ai_rmf': self.nist_ai_rmf,
            'mitre_d3fend': self.mitre_d3fend,
            'frameworks': self.frameworks,
            'standard_reference': self.standard_reference,
            'recommendation': self.recommendation,
            'finding_count': self.finding_count,
        }


class SkillExecutionException(Exception):
    """Base exception for skill execution errors"""
    pass


class SkillExecutor:
    """
    Execute skill workflows against document sections with full error handling.

    TIER 1 Hardening:
    - Error handling on all pattern operations
    - Timeout protection (5 sec per pattern)
    - Output bounding (100 findings per skill, 500 total)
    - Pattern validation (ReDoS prevention)
    - Comprehensive logging
    """

    # Severity ranking
    SEVERITY_ORDER = {'CRITICAL': 4, 'HIGH': 3, 'MEDIUM': 2, 'LOW': 1}

    # TIER 1 Configuration: Safety limits
    PATTERN_TIMEOUT_SECONDS = 5
    MAX_MATCH_COUNT = 1000
    MAX_FINDINGS_PER_SKILL = 100
    MAX_STEP_TIMEOUTS = 3  # Fail skill if >3 pattern timeouts

    # Pattern library with default patterns
    PATTERN_CHECKS = {
        # AWS IAM patterns
        'aws_wildcard_action': {
            'pattern': r'"(?:Action|action)"\s*:\s*["\']?\*["\']?',
            'issue': 'Overly permissive IAM action (Action: *)',
            'severity': 'CRITICAL',
        },
        'aws_wildcard_resource': {
            'pattern': r'"(?:Resource|resource)"\s*:\s*["\']?\*["\']?',
            'issue': 'Overly permissive resource scope (Resource: *)',
            'severity': 'CRITICAL',
        },
        'aws_inline_policy': {
            'pattern': r'AWS::IAM::(?:UserPolicy|RolePolicy)',
            'issue': 'Inline IAM policy used (should use managed policies)',
            'severity': 'HIGH',
        },
        # Network patterns
        'permit_any_any': {
            'pattern': r'permit\s+(?:ip|tcp|udp)\s+any\s+any',
            'issue': 'Over-permissive firewall rule (permit any any)',
            'severity': 'CRITICAL',
        },
        'telnet_enabled': {
            'pattern': r'(?:telnet|Telnet)\s+(?:enabled|allowed|open)',
            'issue': 'Telnet cleartext protocol enabled (should use SSH)',
            'severity': 'CRITICAL',
        },
        'ftp_backup': {
            'pattern': r'(?:FTP|ftp)\s+(?:backup|upload|config)',
            'issue': 'FTP used for sensitive transfer (should use SFTP/SCP)',
            'severity': 'CRITICAL',
        },
        'snmpv1_v2c': {
            'pattern': r'SNMPv(?:1|2c)|community\s+string',
            'issue': 'SNMPv1/v2c cleartext protocol used (should use SNMPv3)',
            'severity': 'HIGH',
        },
        # Application patterns
        'no_mfa_admin': {
            'pattern': r'(?:admin|administrator).*(?:login|access)\s+(?:without|no)\s+(?:MFA|2FA)',
            'issue': 'Administrative access without MFA enforcement',
            'severity': 'CRITICAL',
        },
        'credentials_in_code': {
            'pattern': r'(?:password|secret|api.?key|token)\s*=\s*["\'][^"\']{6,}["\']',
            'issue': 'Credentials hardcoded in configuration/code',
            'severity': 'CRITICAL',
        },
        'no_csrf_token': {
            'pattern': r'(?:form|POST)\s+(?:without|no)\s+(?:CSRF|csrf)\s+(?:token|protection)',
            'issue': 'Missing CSRF token protection on state-changing requests',
            'severity': 'HIGH',
        },
    }

    def __init__(self, skill: SkillMetadata):
        """
        Initialize executor for a skill.

        TIER 1: Validates all patterns at init time

        Args:
            skill: SkillMetadata loaded from skill index
        """
        self.skill = skill
        self.findings: List[SkillFinding] = []
        self.timeout_count = 0

        # Validate all patterns on initialization
        self.pattern_db = PatternDatabase()
        for name, pattern_def in self.PATTERN_CHECKS.items():
            if not self.pattern_db.add_pattern(name, pattern_def.copy()):
                logger.warning(
                    f"Skill '{skill.name}': Pattern '{name}' failed validation. "
                    "This pattern will be skipped during execution."
                )

        logger.info(
            f"Skill executor initialized for '{skill.name}' "
            f"with {len(self.pattern_db.patterns)} validated patterns"
        )

    def execute(self, section_text: str, section_name: str = "") -> List[SkillFinding]:
        """
        Execute skill workflow against a document section.

        TIER 1: Bounded output, error recovery

        Args:
            section_text: Text content of document section
            section_name: Name/title of section for context

        Returns:
            List of findings generated by skill execution
        """
        findings = []

        if not section_text:
            logger.debug(f"Empty section text for '{section_name}'")
            return findings

        # Safety check on input size
        if len(section_text) > 10_000_000:  # 10 MB
            logger.warning(
                f"Section '{section_name}' is very large ({len(section_text)} bytes). "
                "Truncating to prevent memory issues."
            )
            section_text = section_text[:10_000_000]

        try:
            # Extract workflow steps from skill markdown
            workflow_steps = self._extract_workflow_steps(self.skill.full_content)
            logger.debug(f"Extracted {len(workflow_steps)} workflow steps")

            # Execute pattern matching for each workflow step
            for step_num, step in enumerate(workflow_steps, 1):
                # Stop if we've hit max findings for this skill
                if len(findings) >= self.MAX_FINDINGS_PER_SKILL:
                    logger.info(
                        f"Skill '{self.skill.name}' reached finding limit "
                        f"({self.MAX_FINDINGS_PER_SKILL}). Stopping execution."
                    )
                    break

                step_findings = self._execute_step(
                    section_text,
                    step,
                    step_num,
                    section_name
                )
                findings.extend(step_findings)

            logger.info(
                f"Skill '{self.skill.name}' execution complete: "
                f"{len(findings)} findings from section '{section_name}'"
            )

        except Exception as e:
            logger.error(
                f"Unexpected error executing skill '{self.skill.name}': {e}",
                exc_info=True
            )
            # Return partial findings collected before error
            return findings

        return findings

    def _extract_workflow_steps(self, skill_content: str) -> List[Dict[str, str]]:
        """
        Extract workflow steps from skill markdown.

        Args:
            skill_content: Full SKILL.md content

        Returns:
            List of workflow steps with description and checks
        """
        steps = []

        try:
            # Split by H3 headers (### Step N:)
            parts = re.split(r'### Step \d+:?\s*(.+?)\n', skill_content)

            # Process pairs of (title, content)
            for i in range(1, len(parts), 2):
                if i + 1 < len(parts):
                    title = parts[i].strip()
                    content = parts[i + 1].strip()

                    steps.append({
                        'title': title,
                        'content': content,
                        'patterns': self._extract_patterns(content)
                    })
        except Exception as e:
            logger.error(f"Error extracting workflow steps: {e}")

        return steps

    def _extract_patterns(self, step_content: str) -> List[str]:
        """
        Extract security patterns to check from step content.

        Args:
            step_content: Content of a workflow step

        Returns:
            List of pattern names to check
        """
        patterns = []

        try:
            # Check which patterns are relevant to this step
            for pattern_name in self.pattern_db.patterns.keys():
                # Simple heuristic: check if pattern keywords appear in step
                keywords = pattern_name.replace('_', ' ').split()
                if any(kw in step_content.lower() for kw in keywords):
                    patterns.append(pattern_name)
        except Exception as e:
            logger.warning(f"Error extracting patterns: {e}")

        return patterns

    def _execute_step(
        self,
        section_text: str,
        step: Dict,
        step_num: int,
        section_name: str
    ) -> List[SkillFinding]:
        """
        Execute a single workflow step with full error handling and timeouts.

        TIER 1: Errors handled, timeouts enforced, findings bounded

        Args:
            section_text: Document section to analyze
            step: Workflow step with title, content, patterns
            step_num: Step number for finding ID
            section_name: Name of section being analyzed

        Returns:
            List of findings from this step
        """
        findings = []

        # Check patterns defined for this step
        for pattern_name in step.get('patterns', []):
            if pattern_name not in self.pattern_db.patterns:
                logger.debug(f"Pattern '{pattern_name}' not found in database")
                continue

            try:
                pattern_def = self.pattern_db.patterns[pattern_name]
                pattern_str = pattern_def['pattern']
                issue = pattern_def['issue']
                severity = pattern_def['severity']

                # Compile pattern with error handling
                try:
                    compiled_pattern = re.compile(pattern_str)
                except re.error as e:
                    logger.error(
                        f"Invalid regex for pattern '{pattern_name}': {e}. "
                        f"Skill: {self.skill.name}"
                    )
                    continue

                # Search with timeout protection
                try:
                    matches = self._find_matches_with_timeout(
                        compiled_pattern,
                        section_text,
                        timeout_seconds=self.PATTERN_TIMEOUT_SECONDS
                    )
                except TimeoutError:
                    self.timeout_count += 1
                    logger.warning(
                        f"Pattern timeout for '{pattern_name}' on section '{section_name}' "
                        f"(skill: {self.skill.name}). "
                        f"Text length: {len(section_text)} bytes"
                    )
                    if self.timeout_count >= self.MAX_STEP_TIMEOUTS:
                        logger.error(
                            f"Skill '{self.skill.name}' exceeded timeout limit. "
                            "Stopping execution."
                        )
                        return findings
                    continue

                # Safety cap on match count
                if len(matches) > self.MAX_MATCH_COUNT:
                    logger.warning(
                        f"Pattern '{pattern_name}' produced {len(matches)} matches "
                        f"(capped at {self.MAX_MATCH_COUNT})"
                    )
                    matches = matches[:self.MAX_MATCH_COUNT]

                # Generate findings from matches
                for match_idx, match in enumerate(matches):
                    try:
                        if len(findings) >= self.MAX_FINDINGS_PER_SKILL:
                            logger.debug(
                                f"Reached max findings for this skill. "
                                f"Skipping remaining matches."
                            )
                            break

                        start = max(0, match.start() - 100)
                        end = min(len(section_text), match.end() + 100)
                        evidence_excerpt = section_text[start:end].strip()

                        finding_id = (
                            f"{self.skill.name}_{section_name}_"
                            f"step{step_num}_match{match_idx}"
                        )

                        finding = SkillFinding(
                            id=finding_id,
                            skill_id=self.skill.name,
                            skill_name=self.skill.name,
                            skill_domain=self.skill.domain,
                            issue=issue,
                            severity=severity,
                            evidence_excerpt=evidence_excerpt[:200],
                            mitre_attack=self.skill.mitre_attack.copy(),
                            nist_csf=self.skill.nist_csf.copy(),
                            nist_ai_rmf=self.skill.nist_ai_rmf.copy(),
                            mitre_d3fend=self.skill.mitre_d3fend.copy(),
                            frameworks=self.skill.frameworks.copy(),
                            standard_reference=self.skill.domain,
                            recommendation=f"See {self.skill.name} SKILL.md for remediation steps",
                            finding_count=match_idx + 1,
                        )

                        findings.append(finding)
                    except Exception as e:
                        logger.error(
                            f"Error creating finding from match {match_idx}: {e}. "
                            f"Skill: {self.skill.name}, Pattern: {pattern_name}"
                        )
                        continue

            except Exception as e:
                logger.error(
                    f"Unexpected error executing pattern '{pattern_name}' "
                    f"in skill '{self.skill.name}': {e}",
                    exc_info=True
                )
                continue

        return findings

    def _find_matches_with_timeout(
        self,
        compiled_pattern,
        text: str,
        timeout_seconds: float = 5
    ) -> List:
        """
        Find regex matches with timeout protection.

        On Unix: uses signal-based timeout
        On Windows: uses threading-based timeout

        Args:
            compiled_pattern: Pre-compiled regex pattern
            text: Text to search
            timeout_seconds: Maximum execution time

        Returns:
            List of match objects

        Raises:
            TimeoutError: If matching exceeds timeout
        """
        if sys.platform == 'win32':
            return self._find_matches_threaded(compiled_pattern, text, timeout_seconds)
        else:
            return self._find_matches_signal(compiled_pattern, text, timeout_seconds)

    def _find_matches_signal(self, pattern, text: str, timeout_sec: float):
        """Unix-based timeout using signal.alarm"""
        import signal

        def timeout_handler(signum, frame):
            raise TimeoutError(f"Regex matching exceeded {timeout_sec} seconds")

        # Set signal handler
        old_handler = signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(int(timeout_sec) + 1)

        try:
            matches = list(pattern.finditer(text, re.IGNORECASE))
            return matches
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, old_handler)

    def _find_matches_threaded(self, pattern, text: str, timeout_sec: float):
        """Windows-compatible threading-based timeout"""
        result_queue = queue.Queue()

        def worker():
            try:
                matches = list(pattern.finditer(text, re.IGNORECASE))
                result_queue.put(('success', matches))
            except Exception as e:
                result_queue.put(('error', e))

        thread = threading.Thread(target=worker, daemon=True)
        thread.start()
        thread.join(timeout=timeout_sec)

        if thread.is_alive():
            raise TimeoutError(f"Regex matching exceeded {timeout_sec} seconds")

        try:
            status, result = result_queue.get_nowait()
            if status == 'error':
                raise result
            return result
        except queue.Empty:
            raise TimeoutError("Thread result not available")

    @staticmethod
    def filter_findings(
        findings: List[SkillFinding],
        min_severity: Optional[str] = None,
        domains: Optional[List[str]] = None
    ) -> List[SkillFinding]:
        """
        Filter findings by severity and domain.

        Args:
            findings: List of findings to filter
            min_severity: Minimum severity level
            domains: List of allowed domains

        Returns:
            Filtered findings
        """
        filtered = findings

        if min_severity and min_severity in SkillExecutor.SEVERITY_ORDER:
            min_score = SkillExecutor.SEVERITY_ORDER[min_severity]
            filtered = [
                f for f in filtered
                if SkillExecutor.SEVERITY_ORDER.get(f.severity, 0) >= min_score
            ]

        if domains:
            domains_lower = [d.lower() for d in domains]
            filtered = [
                f for f in filtered
                if f.skill_domain.lower() in domains_lower
            ]

        return filtered

    @staticmethod
    def deduplicate_findings(findings: List[SkillFinding]) -> List[SkillFinding]:
        """
        Remove duplicate findings.

        Args:
            findings: List of findings

        Returns:
            Deduplicated findings (keeps first occurrence)
        """
        seen = set()
        unique = []

        for finding in findings:
            # Create fingerprint from issue + evidence
            fingerprint = (
                finding.skill_id,
                finding.issue,
                finding.severity,
                finding.evidence_excerpt[:50]
            )

            if fingerprint not in seen:
                seen.add(fingerprint)
                unique.append(finding)

        return unique


if __name__ == '__main__':
    # Example usage with error handling
    from skill_index import SkillIndex

    print("=" * 60)
    print("SkillExecutor v2 - TIER 1 Hardening Test")
    print("=" * 60)

    # Load index
    try:
        index = SkillIndex('/tmp/work/skills')

        # Get a skill
        skill = index.get_skill_by_name('detecting-cloud-iam-misconfigurations')
        if skill:
            executor = SkillExecutor(skill)

            # Test section with wildcard pattern
            test_section = """
            AWS IAM Configuration:
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "*",
                  "Resource": "*"
                }
              ]
            }
            """

            print("\n[Test] Executing skill on sample configuration...")
            findings = executor.execute(test_section, "iam_config")
            print(f"Found {len(findings)} issues:")
            for finding in findings[:3]:
                print(f"  [{finding.severity}] {finding.issue}")
                print(f"      Evidence: {finding.evidence_excerpt[:60]}...")

            print("\n✅ SkillExecutor v2 operational!")
        else:
            print("❌ Could not load skill")
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
